### ISSUE TITLE
PKI Express is not installed

### ISSUE THREAD

**Issue by denebtech** [LacunaSoftware/PkiExpressPython#1]
Good afternoon, I have been testing the PkiExpressLacunaSamples for python following the steps recommended by the repository, but it throws the following error in the image?

![image](https://user-images.githubusercontent.com/38706103/89232814-b1b2a980-d5be-11ea-8f45-989452562ef5.png)

In my case I use Pipfile (from pipenv) to keep track of the libraries and update several of them. It is the following:

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
flask = "==1.1.2"
flask-session = "==0.3.2"
itsdangerous = "==0.24"
jinja2 = "==2.11.2"
markupsafe = "==1.1.1"
werkzeug = "==0.15.3"
click = "==7.1.2"
wheel = "==0.34.2"
docopt = "==0.6.2"
restpki-client = "==1.1.1"
pkiexpress = "==1.6.2"

[requires]
python_version = "3.7"
```

What could be the problem? From already thank you very much.

**Comment by MimyS** [comment]
Have you installed the PKI Express external application?

http://docs.lacunasoftware.com/articles/pki-express/setup/index.html

**Comment by denebtech** [comment]
Buscaba una solución con decker, y me tope con otro de sus repo:

https://github.com/LacunaSoftware/docker-images/tree/samples

Asi que utilice estos para hacer arrancar la app de ejemplo de python en Flask. No queria instalarlo localmente porque la idea era dockerizar la solución. Gracias.
